package Trigonometric;

/**
 * 
 * This class file is for handling custom exception generated by Power Function.
 * 
 * @author ASE Group 15
 * Kavisha Kiritbhai Solanki (105221731)
 * Arti Bipinbhai Vekaria (110028349)
 * Yash Savjibhai Anghan (110038518)
 * Nikunj Labhubhai Chopda (110030130)
 * 
 * 
 * @version 1.0.0
 * 
 */

public class Power_Exception_Handler extends Exception
{
	public Power_Exception_Handler(String s)
	{
		super(s);
	}
}
